# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 069ddf274995ede8251f591ed9ebded0664f2ed78885f223be7dba4a8b9239c27b89f639a05f8719ebc35d18e1990b4f64e52d0b5b113c16a65bdb88b964d23f

test:
  secret_key_base: 70add052e3e6d01b37ecc89844ac52ef2bc877dc8fc0aa45f8ca64b3d44545eeb50fec0d3b53fd943175f086a2510549f7fbd966bd7dcfb6db1321a2b4583874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
